variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy
  - prepare

#jobs:
build_images:
  stage: build
  needs: [ ]
  tags:
    - docker
    - docker-compose
  script:
    - docker-compose -f docker-compose.base.yml build --pull --parallel --force-rm --no-cache
  except:
    - schedules

deploy_containers:
  stage: deploy
  needs: [ "build_images" ]
  environment:
    name: production
  tags:
    - deploy
    - docker
    - docker-compose
  script:
    - docker-compose -f docker-compose.base.yml -f $CONFIG_DOCKER_COMPOSE down
    - docker-compose -f docker-compose.base.yml -f $CONFIG_DOCKER_COMPOSE up -d --remove-orphans
  except:
    - schedules

collect_container_logs:
  stage: deploy
  needs: [ "deploy_containers" ]
  environment:
    name: production
  when: manual
  tags:
    - deploy
    - docker
    - docker-compose
  script:
    - docker-compose -f docker-compose.base.yml logs redis
    - docker-compose -f docker-compose.base.yml logs nginx
    - docker-compose -f docker-compose.base.yml logs php-fpm
  except:
    - schedules

warmup_container_caches:
  stage: prepare
  needs: [ "deploy_containers" ]
  environment:
    name: production
  tags:
    - deploy
    - docker
    - docker-compose
  script:
    - docker-compose -f docker-compose.base.yml -f $CONFIG_DOCKER_COMPOSE exec -T php-fpm sh -c "./bin/console cache:warmup --CI --force-index"
  except:
    - schedules

refresh_container_caches:
  stage: prepare
  needs: [ "deploy_containers" ]
  environment:
    name: production
  tags:
    - deploy
    - docker
    - docker-compose
  script:
    - docker-compose -f docker-compose.base.yml -f $CONFIG_DOCKER_COMPOSE exec -T php-fpm sh -c "./bin/console cache:warmup --CI"
  only:
    - schedules
