version: '3.0'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./public/:/app/public/:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        - APP_ENV=${APP_ENV:-prod}
        - PHP_VERSION=${PHP_VERSION:-8.2}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    volumes:
      - ./:/app/:rw
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/zzzz_xdebug.ini:ro
